# Static configuration

log:
  level: TRACE

global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true
  debug: true

metrics:
  prometheus: {}

entryPoints:
  web:
   address: ":6688"

providers:
  # https://doc.traefik.io/traefik/providers/file/
  file:
    watch: true
    filename: "dyn.yaml"

experimental:
  localPlugins:
    demowasm:
      moduleName: github.com/traefik/plugindemowasm
