name: Release

on:
  push:
    tags:
        - "v*.*.*"

jobs:
  main:
    name: Release process
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.21

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install tinygo
        uses: acifani/setup-tinygo@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --timeout=10m
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPO }}
